# -*- coding: utf-8 -*-
"""Python Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15FSi_tUbZK3pKmG0z3Q77PVQbADm3rOt
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel("/content/Countries Data Python Project.xlsx")
print(df.head())

df['Country Name'].value_counts()

df[~(df['Country Name'].isin(['Cyprus','Azerbaijan','Kazakhstan','Turkiye']))&(df['Continent Name']=="Europe")]

from google.colab import files
files.download('/content/Countries Data For Python Project.xlsx')

from google.colab import drive
drive.mount('/content/drive')

print("Here Is The Columns Of The Dataset: ",df.columns)
print("Here Is The Shape of The Dataset: ",df.shape)

df.info()
df.describe()

df.isnull().sum()
df.duplicated().sum()

# Step 1 — Understanding Countries and Years
print("Total Countries:", df['Country Name'].nunique())
print("Total Continents:", df['Continent Name'].nunique())
print("Year Range:", df['Year'].min(), "-", df['Year'].max())

# Step 2 — Top & Bottom 10 Countries With Highest And Lowest Ease Of Doing Business.
EDB_avg = df.groupby('Country Name')['Ease of Doing Business'].mean().sort_values(ascending=False)

top_10_EDB = EDB_avg.head()
bottom_10_EDB = EDB_avg.tail()

# Top 10 Countries
plt.figure(figsize=(8, 5))
top_10_EDB.plot(kind='bar', color='blue')
plt.title('Top 10 Countries by Ease of Doing Business (Average)')
plt.ylabel('Average Ease of Doing Business Score')
plt.xticks(rotation=0, ha='center')
plt.tight_layout()
plt.show()

# Bottom 10 Countries
plt.figure(figsize=(8, 5))
bottom_10_EDB.plot(kind='bar', color='red')
plt.title('Bottom 10 Countries by Ease of Doing Business (Average)')
plt.ylabel('Average Ease of Doing Business Score')
plt.xticks(rotation=0, ha='center')
plt.tight_layout()
plt.show()

# Step 3 — Each Sector Contribution In Whole World Analysis.

# Agriculture vs Industry vs Service

sector_cols = ['Agriculture (% GDP)','Industry (% GDP)','Service (% GDP)']

df[sector_cols].mean().plot(kind='bar')
plt.title("Average Economic Sector Contribution")
plt.show()

# Step 4 — GDP Growth Over Time In World.
gdp_year = df.groupby("Year")["GDP"].mean()

plt.figure(figsize=(10,5))
plt.plot(gdp_year)
plt.title("Average GDP Over Time")
plt.xlabel("Year")
plt.ylabel("GDP")
plt.show()

# Step 5 Top-5 & Bottom-5 Importing And Exporting Countries In The World.

Imp_Exp_Country = df.groupby('Country Name')[['Import','Export']].mean()

# Top 5 Exporting Countries
top_5_export = Imp_Exp_Country.sort_values(by='Export', ascending=False).head(5)

# Bottom 5 Exporting Countries
bottom_5_export = Imp_Exp_Country.sort_values(by='Export', ascending=False).tail(5)

# Top 5 Importing Countries
top_5_import = Imp_Exp_Country.sort_values(by='Import', ascending=False).head(5)

# Bottom 5 Importing Countries
bottom_5_import = Imp_Exp_Country.sort_values(by='Import', ascending=False).tail(5)

# Combine top 5 imports and exports for clustered bar chart
top_5_combined = Imp_Exp_Country.nlargest(5, ['Export', 'Import'])
plt.figure(figsize=(12, 7))
top_5_combined[['Export', 'Import']].plot(kind='bar', figsize=(12, 7))
plt.title('Top 5 Countries by Average Export and Import')
plt.ylabel('Average Value')
plt.xticks(rotation=0, ha='center')
plt.show()

# Combine bottom 5 imports and exports for clustered bar chart
bottom_5_combined = Imp_Exp_Country.nsmallest(5, ['Export', 'Import'])
plt.figure(figsize=(12, 7))
bottom_5_combined[['Export', 'Import']].plot(kind='bar', figsize=(12, 7))
plt.title('Bottom 5 Countries by Average Export and Import')
plt.ylabel('Average Value')
plt.xticks(rotation=0, ha='center')
plt.show()

# Step 6 — GDP Per Capita by Continent
plt.figure(figsize=(10,8))
sns.boxplot(x="Continent Name", y="GDP Per Capita", data=df)
plt.xticks(rotation=0)
plt.show()

# Step 7 — Correlation Analysis (Very Important in EDA)
plt.figure(figsize=(14,10))
sns.heatmap(df.select_dtypes(include=np.number).corr(), cmap="coolwarm", annot=True)
plt.title("Correlation Matrix")
plt.show()

# This will show relationships like:
# GDP vs Population
# Education vs GDP
# Health vs GDP
# Inflation vs Unemployment

# Step 8 — Continent Wise Land Size.

continent_land = df.groupby('Continent Name')['Land'].sum().sort_values(ascending=False)

plt.figure(figsize=(10,6))
continent_land.plot(kind='bar', color='lightgreen')
plt.title('Continent Wise Land Size')
plt.ylabel('Total Land Area (sq km)')
plt.xticks(rotation=0, ha='center')
plt.show()

# Step 9 — Population Density vs GDP Per Capita
sns.scatterplot(x="Population Density", y="GDP Per Capita", data=df)
plt.title("Population Density vs GDP Per Capita")
plt.show()

# Step 10 — Top 10 Richest Countries
top10 = df.groupby("Country Name")["GDP Per Capita"].mean().sort_values(ascending=False).head(10)
plt.figure(figsize=(11,6))
top10.plot(kind="bar")
plt.title("Top 10 Richest Countries (Avg GDP Per Capita)")
plt.xticks(rotation=0,ha='center')
plt.show()

# Step 11 — Best Visualization for EDA (Very Impressive)

# Pairplot:

sns.pairplot(df[['GDP Per Capita','Inflation Rate','Unemployment','Education Expenditure (% GDP)']])

# Step 12 - Top & Bottom 5 Country By Population
TP5 = df.groupby('Country Name')['Population'].sum().sort_values(ascending=False).head(5)
plt.figure(figsize=(10, 6))
TP5.plot(kind='bar', color='olivedrab')
plt.title('Top 5 Countries By Population')
plt.ylabel('Total Population')
plt.xticks(rotation=0, ha='center')
plt.show()
print("/nBottom")
BT5 = df.groupby('Country Name')['Population'].sum().sort_values(ascending=False).tail(5)
plt.figure(figsize=(10, 6))
BT5.plot(kind='bar', color='slateblue')
plt.title('Bottom 5 Countries By Population')
plt.xlabel('Country Name')
plt.ylabel('Total Population')
plt.xticks(rotation=0, ha='center')
plt.show()

# Step 13 - Top 10 Countries With Highest Positive Net Trade In 2022.
year_2022 = df[df['Year'] == 2022]
NT_2022 = year_2022[year_2022['Net Trade'] > 0]
Top_10_2022 = NT_2022.groupby('Country Name')['Net Trade'].sum().sort_values(ascending=False).head(10)

plt.figure(figsize=(13, 7))
Top_10_2022.plot(kind='bar', color='teal')
plt.title('Top 10 Countries by Positive Net Trade in 2022')
plt.ylabel('Net Trade Volume')
plt.xticks(rotation=0, ha='center')
plt.tight_layout()
plt.show()

# Step 14 - Top 10 Countries by Expenditure on Health And Education.
year_2022 = df[df['Year'] == 2022]
NT_2022 = year_2022[year_2022[['Health Expenditure (% GDP)','Education Expenditure (% GDP)']] > 0]
HE10 = df.groupby('Country Name')[['Health Expenditure (% GDP)','Education Expenditure (% GDP)']].mean().sort_values(by=['Health Expenditure (% GDP)', 'Education Expenditure (% GDP)'],ascending=False).head(10)

plt.figure(figsize=(13, 6))
HE10.plot(kind='bar', ax=plt.gca(), color=['skyblue', 'lightcoral'])
plt.title('Top 10 Countries by Expenditure on Health And Education.')
plt.ylabel('Expenditure (% GDP)')
plt.xticks(rotation=0, ha='center')
plt.tight_layout()
plt.show()

# Step 15 - Top 10 Countries With Highest And Lowest Inflation Rate In 2022.

inflation_2022 = df[df['Year'] == 2022]
inflation_avg_2022 = inflation_2022.groupby('Country Name')['Inflation Rate'].mean().sort_values(ascending=False)

# Top 10 Countries with Highest Inflation Rate in 2022
top_10_inflation = inflation_avg_2022.head(10)
plt.figure(figsize=(13, 6))
top_10_inflation.plot(kind='bar', color='darkred')
plt.title('Top 10 Countries by Average Inflation Rate in 2022 (Highest)')
plt.ylabel('Average Inflation Rate')
plt.xticks(rotation=0, ha='center')
plt.tight_layout()
plt.show()

print("\n")

# Top 10 Countries with Lowest Inflation Rate in 2022
bottom_10_inflation = inflation_avg_2022.tail(10).sort_values(ascending=True) # Sort again for ascending display
plt.figure(figsize=(13, 6))
bottom_10_inflation.plot(kind='bar', color='darkgreen')
plt.title('Top 10 Countries by Average Inflation Rate in 2022 (Lowest)')
plt.ylabel('Average Inflation Rate')
plt.xticks(rotation=0, ha='center')
plt.tight_layout()
plt.show()

# Step 16 - Top 10 Countries With Highest And Lowest Unemployement Rate In 2022.

Unemployment_2022 = df[df['Year'] == 2022]
Unemployment_avg_2022 = inflation_2022.groupby('Country Name')['Unemployment'].mean().sort_values(ascending=False)

# Top 10 Countries with Highest Inflation Rate in 2022
top_10_Unemployment = Unemployment_avg_2022.head(10)
plt.figure(figsize=(13, 6))
top_10_Unemployment.plot(kind='bar', color='crimson')
plt.title('Top 10 Countries by Average Unemployment Rate in 2022 (Highest)')
plt.ylabel('Average Unemployment Rate')
plt.xticks(rotation=0, ha='center')
plt.tight_layout()
plt.show()

print("\n")

# Top 10 Countries with Lowest Inflation Rate in 2022
bottom_10_Unemployment = Unemployment_avg_2022.tail(10).sort_values(ascending=True) # Sort again for ascending display
plt.figure(figsize=(13, 6))
bottom_10_Unemployment.plot(kind='bar', color='forestgreen')
plt.title('Top 10 Countries by Average Unemployment Rate in 2022 (Lowest)')
plt.ylabel('Average Unemployment Rate')
plt.xticks(rotation=0, ha='center')
plt.tight_layout()
plt.show()

# Step - 17 Top 10 Countries With Highest & Lowest Population Density in 2022.

population_density_2022 = df[df['Year'] == 2022]
population_density_avg_2022 = population_density_2022.groupby('Country Name')['Population Density'].mean().sort_values(ascending=False)

# Top 10 Countries with Highest Population Density in 2022
top_10_population_density = population_density_avg_2022.head(10)
plt.figure(figsize=(13, 6))
top_10_population_density.plot(kind='bar', color='orangered')
plt.title('Top 10 Countries by Average Population Density in 2022 (Highest)')
plt.ylabel('Average Population Density')
plt.xticks(rotation=0, ha='center')
plt.tight_layout()
plt.show()

print("\n")

# Top 10 Countries with Lowest Population Density in 2022
bottom_10_population_density = population_density_avg_2022.tail(10).sort_values(ascending=True)
plt.figure(figsize=(13, 6))
bottom_10_population_density.plot(kind='bar', color='darkgoldenrod')
plt.title('Top 10 Countries by Average Population Density in 2022 (Lowest)')
plt.ylabel('Average Population Density')
plt.xticks(rotation=0, ha='center')
plt.tight_layout()
plt.show()

# Step - 18

df.columns

# Step 1 — Key Insights Section (Important for Report)

# Example insights you might find:

# Countries with higher education expenditure tend to have higher GDP per capita.

# Service sector dominates global economies.

# Population density doesn't strongly correlate with GDP per capita.

# Exports and imports are highly correlated.